### ISSUE TITLE
针对简化字字表的建议

### ISSUE THREAD

**Issue by shinzoqchiuq** [Hynuza/fengyo#1]
这个仓库的 dict 文件用是简化字。对于简化字字表，我有以下几个建议：

1.

https://github.com/Hynuza/fengyo/blob/bd9150f14f3bf02ea738b288612b1fb1bfca615f/fengyo.dict.yaml#L10

https://github.com/Hynuza/fengyo/blob/bd9150f14f3bf02ea738b288612b1fb1bfca615f/fengyo_word.dict.yaml#L10

上面两行导入了 Rime 预设的词汇表 [八股文](https://github.com/rime/rime-essay)。这个词汇表用的是繁体字，直接导入会有繁简混合的问题。建议改为：

```yaml
vocabulary: essay-zh-hans
```

导入 [简化字八股文](https://github.com/rime/rime-essay-simp)。同时把 `essay-zh-hans.txt` 放到仓库。

2.

https://github.com/Hynuza/fengyo/blob/bd9150f14f3bf02ea738b288612b1fb1bfca615f/fengyo.schema.yaml#L26

https://github.com/Hynuza/fengyo/blob/bd9150f14f3bf02ea738b288612b1fb1bfca615f/fengyo.schema.yaml#L27

这里的 26 和 27 行是繁转简设置。如果只用简化字的话，可以删掉这两行。如果确实需要输入繁体字，也应该设置简转繁而非繁转简。

**Comment by Hynuza** [comment]
非常感谢指导！已更新所有相关文件并添加  essay-zh-hans.txt 
https://github.com/Hynuza/fengyo
